name: Deploy to Amazon S3

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

env:
  AWS_REGION: ap-northeast-1
  AWS_S3_BUCKET: daisan-kazoku-homepage
  AWS_CLOUDFRONT_DISTRIBUTION_ID: E1QTN6UTQ90A36

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - run: yarn install
      - run: yarn build

      - name: Deploy to S3
        run: |
          aws s3 sync ./out s3://${{ env.AWS_S3_BUCKET }} --delete

      - name: Purge CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
